version: "3.7"
services:
  api_service:
    build: .
    working_dir: /app
    restart: always
    ports:
      - 8090:8090
    networks:
      - springapimysql-net
    depends_on:
      - mysqldb

    volumes:
      - .:/app
      - .m2:/root/.m2

  mysqldb:
    image: "mysql/mysql-server:8.0"
    restart: always
    ports:
      - 3310:3310
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: spring
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3310
    container_name: mysqldb
networks:
  springapimysql-net: